### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by Bukashk0zzz**
Added support of swiftmailer version 6

### CODE REVIEW

**Comment by Bukashk0zzz** [comment]
@hellogerard Thank you for your lib. Please made my dreams come true) Merge this PR.

**Comment by Bukashk0zzz** [comment]
@hellogerard ping

**Comment by hellogerard** [comment]
Released as v3.3.1!

**Comment by Bukashk0zzz** [comment]
Thank you.

**Pull request merged**
