### PR TITLE
Allow schedule to be an array (keys: m, h, dom, mon & dow)

### PR DESCRIPTION
**Pull request by joonaskaskisola**

### CODE REVIEW

**Comment by hellogerard** [comment]
@joonaskaskisola Thanks for the PR. I don't do much PHP these days. Is this a standard somewhere? I don't see much value in adding another scheduling format unless it's widely used. The `crontab` syntax is very powerful and should suffice for any scenario.

**Comment by joonaskaskisola** [comment]
Not a standard, more of a nice to have feature and I'd say somewhat easier to manage in some cases. Great tool btw!

**Comment by garethellis36** [comment]
Hi @joonaskaskisola - please check out my new library that I wrote specifically for making management of Jobby schedules a bit nicer and more expressive :)
https://github.com/garethellis36/crontab-schedule-generator

**Comment by hellogerard** [comment]
I think @garethellis36 has a good alternative for this.

**Pull request closed without merging**
