### PR TITLE
Check if job is due to run in main process

### PR DESCRIPTION
**Pull request by garethellis36**
See #45 

[x] Adds `ScheduleChecker` class for determining if a job is due to run
[x] Uses `ScheduleChecker` in `BackgroundJob::shouldRun()`
[x] Moves use of `ScheduleChecker` to main process (`Jobby::run()`)

NB this pull request relies on changes made in #61

### CODE REVIEW

**Comment by garethellis36** [comment]
Now ready for your comments @hellogerard  :smiley: 

Point for discussion - if `ScheduleChecker::isDue()` is being checked in `Jobby::run()`, does it also need to be checked in `BackgroundJob::shouldRun()`?

**Comment by hellogerard** [comment]
Thanks for all your work on this PR and the other. Released [jobby 3.1.0](https://packagist.org/packages/hellogerard/jobby)!

**Comment by garethellis36** [comment]
@hellogerard My pleasure. What do you think about the fact that the schedule is now checked in `Jobby::run()` and in `BackgroundJob::shouldRun()`? Should we remove the check from the background task on the basis that it won't run in the first place if it's not due?

**Comment by hellogerard** [comment]
@garethellis36 Ah, sorry, I missed this. 

On one hand, it never hurts to have redundancy. OTOH, I like DRY and SRP, so I think we should take it out. Why not sneak it into #63?

**Comment by garethellis36** [comment]
I created a new PR for it - see #64

**Pull request merged**
