### PR TITLE
Configurable background job

### PR DESCRIPTION
**Pull request by CarsonF**
Moved logic for running a job to separate file. 

`BackgroundJob` class can now be overridden with _jobClass_ config option.

### CODE REVIEW

**Comment by hellogerard** [comment]
Do you think you can make this work with #48 (that is, make it work for phar files)?  I had just merged that one before this one (for some reason).

**Comment by CarsonF** [comment]
Yeah I'll see if I can take a look. I've never worked with phars before. Since he didn't write any tests, it will be hard for me to verify if I broke something.

**Comment by hellogerard** [comment]
I deleted PRs #48 & #49, so that yours could merge cleanly. (I had to force push `master` but oh well.) I then re-merged #48 & #49 since those were "simpler". I think they're right. Updated to 3.0.0 and released!

**Comment by CarsonF** [comment]
Sorry I've been so busy lately. Unfortunately, this breaks running for PHARs. `BackgroundJob.php` is being invoked directly with cli arguments, but this file doesn't handle them anymore. I'm not sure how PHARs work, but somehow it needs to reference the `bin/run-job` file.

**Comment by hellogerard** [comment]
I had to study that PHAR PR, but I think I got it working in the latest commits.

**Pull request merged**
