### PR TITLE
replace: "mtdowling/cron-expression" with "dragonmantank/cron-expression"

### PR DESCRIPTION
**Pull request by darkalchemy**
This may introduce breaking changes as "dragonmantank/cron-expression" fixes many issues with how the cron expression is processed(according to the [README](https://github.com/dragonmantank/cron-expression)). For me, there are no issues, but I'm not doing anything fancy with it.

All current tests are green.

### CODE REVIEW

**Comment by darkalchemy** [comment]
I would appreciate any comments for or against before merging the pr.

Thanks

**Comment by darkalchemy** [comment]
I have no experience with writing tests, but that is something I am currently studying. For now, if you could write such a test, I would be most grateful. If not, I hope to have enough understanding within a week or so.

**Comment by hellogerard** [comment]
> I have no experience with writing tests, but that is something I am currently studying. For now, if you could write such a test, I would be most grateful. If not, I hope to have enough understanding within a week or so.


Perfect opportunity to learn!

> fix: only retrieve enabled entries, fixes #98

This looks good, but should in its own PR.

**Comment by darkalchemy** [comment]
It shouldn't have been pushed here, I pushed it to my fork.

**Pull request closed without merging**
